#version: '3.8'  # Add version for compatibility

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=boa
      - POSTGRES_PASSWORD=Akabha-01
      - POSTGRES_USER=kavithabharathiraja
    ports:
      - '5432:5432'

  service:  # Name your Spring Boot application service
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/boa  # Using the docker service name for postgres
      - SPRING_DATASOURCE_USERNAME=kavithabharathiraja
      - SPRING_DATASOURCE_PASSWORD=Akabha-01
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
